-- NewsTeen75 approved YouTube video feed
create table if not exists public.approved_channels (
  id bigint generated by default as identity primary key,
  channel_name text not null,
  youtube_channel_id text unique,
  youtube_handle text unique,
  youtube_url text not null unique,
  uploads_playlist_id text,
  category text not null default 'General',
  language text not null default 'hi',
  active boolean not null default true,
  last_checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.news_videos (
  id text primary key,
  youtube_video_id text not null unique,
  channel_id bigint not null references public.approved_channels(id) on delete cascade,
  channel_name text not null,
  title text not null,
  description text not null default '',
  thumbnail_url text not null,
  youtube_url text not null,
  category text not null default 'General',
  language text not null default 'hi',
  duration_seconds integer,
  duration_iso text,
  published_at timestamptz not null,
  embeddable boolean not null default true,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.video_ingestion_runs (
  id bigint generated by default as identity primary key,
  status text not null,
  channels_checked integer not null default 0,
  fetched_count integer not null default 0,
  upserted_count integer not null default 0,
  error_message text,
  ran_at timestamptz not null default now()
);

create index if not exists news_videos_published_idx
  on public.news_videos (published_at desc, id desc);

create index if not exists news_videos_channel_published_idx
  on public.news_videos (channel_id, published_at desc);

create index if not exists news_videos_category_published_idx
  on public.news_videos (category, published_at desc);

alter table public.approved_channels enable row level security;
alter table public.news_videos enable row level security;
alter table public.video_ingestion_runs enable row level security;

create or replace function public.get_latest_videos(
  p_limit integer default 20,
  p_before_published_at timestamptz default null,
  p_before_id text default null,
  p_category text default null
)
returns table(
  id text,
  youtube_video_id text,
  title text,
  thumbnail_url text,
  channel_name text,
  channel_id bigint,
  published_at timestamptz,
  duration_seconds integer,
  youtube_url text,
  category text,
  language text
)
language sql
stable
security definer
set search_path = public
as $function$
  select
    v.id,
    v.youtube_video_id,
    v.title,
    v.thumbnail_url,
    v.channel_name,
    v.channel_id,
    v.published_at,
    v.duration_seconds,
    v.youtube_url,
    v.category,
    v.language
  from public.news_videos v
  join public.approved_channels c
    on c.id = v.channel_id
  where
    c.active = true
    and v.status = 'active'
    and v.embeddable = true
    and (p_category is null or p_category = '' or v.category = p_category)
    and (
      p_before_published_at is null
      or (v.published_at, v.id) <
         (p_before_published_at, coalesce(p_before_id, ''))
    )
  order by v.published_at desc, v.id desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
$function$;

revoke all on function public.get_latest_videos(integer,timestamptz,text,text) from public;
grant execute on function public.get_latest_videos(integer,timestamptz,text,text) to anon, authenticated;
