-- News Teen75 persistent archive + per-user delivery
-- Apply with Supabase migrations before enabling archive sync in GitHub Actions.

create extension if not exists pg_trgm;

create table if not exists public.news_articles (
  id text primary key,
  provider text not null default 'google_news_rss',
  provider_id text,
  canonical_url text not null unique,
  title text not null,
  summary text not null default '',
  image_url text not null default '',
  publisher text not null default '',
  original_url text not null,
  category text not null default '',
  language text not null default 'en',
  title_hi text,
  summary_hi text,
  title_hinglish text,
  summary_hinglish text,
  published_at timestamptz not null,
  ingested_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  story_fingerprint text,
  search_document tsvector generated always as (
    to_tsvector(
      'simple',
      concat_ws(
        ' ',
        coalesce(title, ''),
        coalesce(summary, ''),
        coalesce(category, ''),
        coalesce(publisher, ''),
        coalesce(title_hi, ''),
        coalesce(summary_hi, ''),
        coalesce(title_hinglish, ''),
        coalesce(summary_hinglish, '')
      )
    )
  ) stored
);

create unique index if not exists news_articles_provider_id_uidx
  on public.news_articles(provider, provider_id)
  where provider_id is not null and provider_id <> '';

create index if not exists news_articles_published_idx
  on public.news_articles(published_at desc, id desc);

create index if not exists news_articles_category_published_idx
  on public.news_articles(category, published_at desc, id desc);

create index if not exists news_articles_search_idx
  on public.news_articles using gin(search_document);

create index if not exists news_articles_title_trgm_idx
  on public.news_articles using gin(title gin_trgm_ops);

create index if not exists news_articles_summary_trgm_idx
  on public.news_articles using gin(summary gin_trgm_ops);

create index if not exists news_articles_publisher_trgm_idx
  on public.news_articles using gin(publisher gin_trgm_ops);

create index if not exists news_articles_story_fingerprint_idx
  on public.news_articles(story_fingerprint)
  where story_fingerprint is not null;

create or replace function public.touch_news_article_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists news_articles_touch_updated_at on public.news_articles;
create trigger news_articles_touch_updated_at
before update on public.news_articles
for each row execute function public.touch_news_article_updated_at();

create table if not exists public.article_seen (
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id text not null references public.news_articles(id) on delete cascade,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  dwell_ms integer not null default 1000 check (dwell_ms >= 1000),
  visible_ratio numeric(4,3) not null default 0.5
    check (visible_ratio >= 0.5 and visible_ratio <= 1),
  primary key (user_id, article_id)
);

create index if not exists article_seen_user_time_idx
  on public.article_seen(user_id, last_seen_at desc);

create table if not exists public.saved_articles (
  user_id uuid not null references auth.users(id) on delete cascade,
  article_id text not null references public.news_articles(id) on delete cascade,
  saved_at timestamptz not null default now(),
  primary key (user_id, article_id)
);

create index if not exists saved_articles_user_time_idx
  on public.saved_articles(user_id, saved_at desc);

create table if not exists public.news_ingestion_runs (
  id bigint generated by default as identity primary key,
  ran_at timestamptz not null default now(),
  status text not null check (status in ('success', 'error')),
  fetched_count integer not null default 0,
  feed_count integer not null default 0,
  archived_count integer not null default 0,
  error_message text
);

alter table public.news_articles enable row level security;
alter table public.article_seen enable row level security;
alter table public.saved_articles enable row level security;
alter table public.news_ingestion_runs enable row level security;

drop policy if exists "news articles are publicly readable" on public.news_articles;
create policy "news articles are publicly readable"
on public.news_articles
for select
using (true);

drop policy if exists "users read own seen history" on public.article_seen;
create policy "users read own seen history"
on public.article_seen
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users add own seen history" on public.article_seen;
create policy "users add own seen history"
on public.article_seen
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users update own seen history" on public.article_seen;
create policy "users update own seen history"
on public.article_seen
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "users read own saved stories" on public.saved_articles;
create policy "users read own saved stories"
on public.saved_articles
for select
to authenticated
using (auth.uid() = user_id);

drop policy if exists "users save own stories" on public.saved_articles;
create policy "users save own stories"
on public.saved_articles
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users unsave own stories" on public.saved_articles;
create policy "users unsave own stories"
on public.saved_articles
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.record_article_seen(
  p_article_id text,
  p_dwell_ms integer,
  p_visible_ratio numeric
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if p_dwell_ms < 1000 or p_visible_ratio < 0.5 then
    return;
  end if;

  insert into public.article_seen (
    user_id,
    article_id,
    first_seen_at,
    last_seen_at,
    dwell_ms,
    visible_ratio
  )
  values (
    v_user_id,
    p_article_id,
    now(),
    now(),
    greatest(p_dwell_ms, 1000),
    least(greatest(p_visible_ratio, 0.5), 1)
  )
  on conflict (user_id, article_id)
  do update set
    last_seen_at = excluded.last_seen_at,
    dwell_ms = greatest(public.article_seen.dwell_ms, excluded.dwell_ms),
    visible_ratio = greatest(public.article_seen.visible_ratio, excluded.visible_ratio);
end;
$$;

create or replace function public.merge_guest_seen(
  p_article_ids text[]
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_count integer := 0;
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;

  if p_article_ids is null or cardinality(p_article_ids) = 0 then
    return 0;
  end if;

  insert into public.article_seen (
    user_id,
    article_id,
    first_seen_at,
    last_seen_at,
    dwell_ms,
    visible_ratio
  )
  select
    v_user_id,
    a.id,
    now(),
    now(),
    1000,
    0.5
  from public.news_articles a
  where a.id = any(p_article_ids)
  on conflict (user_id, article_id) do nothing;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

create or replace function public.get_unseen_feed(
  p_category text default null,
  p_limit integer default 20,
  p_before_published_at timestamptz default null,
  p_before_id text default null,
  p_guest_seen_ids text[] default array[]::text[]
)
returns table (
  id text,
  title text,
  summary text,
  image_url text,
  publisher text,
  original_url text,
  category text,
  language text,
  title_hi text,
  summary_hi text,
  title_hinglish text,
  summary_hinglish text,
  published_at timestamptz,
  ingested_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  with candidates as (
    select
      a.*,
      row_number() over (
        partition by coalesce(nullif(a.story_fingerprint, ''), a.id)
        order by a.published_at desc, a.id desc
      ) as story_rank
    from public.news_articles a
    where
      (p_category is null or p_category = '' or a.category = p_category)
      and not (a.id = any(coalesce(p_guest_seen_ids, array[]::text[])))
      and not exists (
        select 1
        from public.article_seen s
        where s.user_id = auth.uid()
          and s.article_id = a.id
      )
      and (
        p_before_published_at is null
        or (a.published_at, a.id) <
           (p_before_published_at, coalesce(p_before_id, ''))
      )
  )
  select
    c.id,
    c.title,
    c.summary,
    c.image_url,
    c.publisher,
    c.original_url,
    c.category,
    c.language,
    c.title_hi,
    c.summary_hi,
    c.title_hinglish,
    c.summary_hinglish,
    c.published_at,
    c.ingested_at
  from candidates c
  where c.story_rank = 1
  order by c.published_at desc, c.id desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
$$;

create or replace function public.search_news(
  p_query text,
  p_limit integer default 20,
  p_offset integer default 0
)
returns table (
  id text,
  title text,
  summary text,
  image_url text,
  publisher text,
  original_url text,
  category text,
  language text,
  title_hi text,
  summary_hi text,
  title_hinglish text,
  summary_hinglish text,
  published_at timestamptz,
  ingested_at timestamptz,
  rank real
)
language sql
stable
security definer
set search_path = public
as $$
  with q as (
    select plainto_tsquery('simple', trim(coalesce(p_query, ''))) as query
  )
  select
    a.id,
    a.title,
    a.summary,
    a.image_url,
    a.publisher,
    a.original_url,
    a.category,
    a.language,
    a.title_hi,
    a.summary_hi,
    a.title_hinglish,
    a.summary_hinglish,
    a.published_at,
    a.ingested_at,
    case
      when trim(coalesce(p_query, '')) = '' then 0::real
      else ts_rank(a.search_document, q.query)
    end::real as rank
  from public.news_articles a
  cross join q
  where
    trim(coalesce(p_query, '')) <> ''
    and (
      a.search_document @@ q.query
      or a.title ilike '%' || trim(p_query) || '%'
      or a.summary ilike '%' || trim(p_query) || '%'
      or a.category ilike '%' || trim(p_query) || '%'
      or a.publisher ilike '%' || trim(p_query) || '%'
    )
  order by
    rank desc,
    a.published_at desc,
    a.id desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

create or replace function public.save_article(
  p_article_id text
)
returns void
language sql
security definer
set search_path = public
as $$
  insert into public.saved_articles(user_id, article_id)
  select auth.uid(), p_article_id
  where auth.uid() is not null
  on conflict (user_id, article_id) do nothing;
$$;

create or replace function public.unsave_article(
  p_article_id text
)
returns void
language sql
security definer
set search_path = public
as $$
  delete from public.saved_articles
  where user_id = auth.uid()
    and article_id = p_article_id;
$$;

create or replace function public.list_saved_articles(
  p_limit integer default 50,
  p_offset integer default 0
)
returns table (
  id text,
  title text,
  summary text,
  image_url text,
  publisher text,
  original_url text,
  category text,
  language text,
  title_hi text,
  summary_hi text,
  title_hinglish text,
  summary_hinglish text,
  published_at timestamptz,
  saved_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    a.id,
    a.title,
    a.summary,
    a.image_url,
    a.publisher,
    a.original_url,
    a.category,
    a.language,
    a.title_hi,
    a.summary_hi,
    a.title_hinglish,
    a.summary_hinglish,
    a.published_at,
    s.saved_at
  from public.saved_articles s
  join public.news_articles a on a.id = s.article_id
  where s.user_id = auth.uid()
  order by s.saved_at desc
  limit least(greatest(coalesce(p_limit, 50), 1), 100)
  offset greatest(coalesce(p_offset, 0), 0);
$$;

revoke all on function public.record_article_seen(text, integer, numeric) from public;
revoke all on function public.merge_guest_seen(text[]) from public;
revoke all on function public.save_article(text) from public;
revoke all on function public.unsave_article(text) from public;
revoke all on function public.list_saved_articles(integer, integer) from public;

grant execute on function public.record_article_seen(text, integer, numeric) to authenticated;
grant execute on function public.merge_guest_seen(text[]) to authenticated;
grant execute on function public.save_article(text) to authenticated;
grant execute on function public.unsave_article(text) to authenticated;
grant execute on function public.list_saved_articles(integer, integer) to authenticated;

grant execute on function public.get_unseen_feed(text, integer, timestamptz, text, text[]) to anon, authenticated;
grant execute on function public.search_news(text, integer, integer) to anon, authenticated;

grant select on public.news_articles to anon, authenticated;
